# Generated by Django 4.2.8 on 2026-03-12 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_parentteachermessage'),
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('semester', models.PositiveIntegerField()),
                ('section', models.CharField(default='A', max_length=10)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('enrollment_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('enrollment_fee_paid', models.BooleanField(default=False)),
                ('enrollment_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('enrollment_deadline', models.DateField(blank=True, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_enrollments', to='accounts.teacherprofile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_enrollments', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-academic_year__year', 'year', 'semester', 'student__user__first_name'],
                'unique_together': {('student', 'course', 'year', 'semester', 'academic_year')},
            },
        ),
    ]
