# Generated by Django 4.2.8 on 2026-03-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_teacherleave_teacherattendance_teacheractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherattendance',
            name='first_activity_time',
            field=models.DateTimeField(blank=True, help_text='Exact time of first activity', null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='last_activity_time',
            field=models.DateTimeField(blank=True, help_text='Exact time of last activity', null=True),
        ),
    ]
