# Generated by Django 4.2.8 on 2026-03-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_teacherattendance_first_activity_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheractivitylog',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('first_login', 'First Login'), ('mark_attendance', 'Mark Student Attendance'), ('create_assignment', 'Create Assignment'), ('grade_exam', 'Grade Exam'), ('send_message', 'Send Message'), ('view_report', 'View Report'), ('dashboard_access', 'Dashboard Access'), ('system_navigation', 'System Navigation'), ('other', 'Other Activity')], max_length=50),
        ),
    ]
