# Generated by Django 4.2.8 on 2026-03-12 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_semesterenrollment'),
        ('accounts', '0002_parentteachermessage'),
        ('attendance', '0004_alter_teacheractivitylog_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofenceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('center_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('center_lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('radius_meters', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('classroom', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='teacheractivitylog',
            name='is_on_campus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacheractivitylog',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='teacheractivitylog',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='teacheractivitylog',
            name='priority_level',
            field=models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='teacheractivitylog',
            name='related_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.attendancesession'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='attendance_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='classes_attended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='classes_scheduled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='device_info',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='location_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='scheduled_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='validation_method',
            field=models.CharField(choices=[('schedule_based', 'Schedule Based'), ('activity_based', 'Activity Based'), ('geolocation', 'Geolocation'), ('biometric', 'Biometric'), ('manual', 'Manual Entry')], default='activity_based', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacheractivitylog',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('first_login', 'First Login'), ('mark_attendance', 'Mark Student Attendance'), ('create_assignment', 'Create Assignment'), ('grade_exam', 'Grade Exam'), ('send_message', 'Send Message'), ('view_report', 'View Report'), ('dashboard_access', 'Dashboard Access'), ('system_navigation', 'System Navigation'), ('classroom_entry', 'Classroom Entry'), ('biometric_scan', 'Biometric Verification'), ('location_check', 'Location Verification'), ('other', 'Other Activity')], max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('on_leave', 'On Leave'), ('partial', 'Partial Attendance')], default='absent', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherleave',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('earned', 'Earned Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('unpaid', 'Unpaid Leave'), ('emergency', 'Emergency Leave')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='teacheractivitylog',
            index=models.Index(fields=['priority_level', 'timestamp'], name='attendance__priorit_201ea4_idx'),
        ),
        migrations.AddField(
            model_name='teacherschedule',
            name='subject_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.teachersubjectassignment'),
        ),
        migrations.AddField(
            model_name='teacherschedule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='accounts.teacherprofile'),
        ),
        migrations.AddField(
            model_name='teacheractivitylog',
            name='related_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.teacherschedule'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherschedule',
            unique_together={('teacher', 'subject_assignment', 'day_of_week', 'start_time')},
        ),
    ]
